-- Capps Apps Command Center · Phase 2 migration + seed bundle
-- Generated by db/dump-seed-sql.ts. Idempotent.

BEGIN;

DROP TABLE IF EXISTS status_snapshots CASCADE;
DROP TABLE IF EXISTS apps CASCADE;

CREATE TABLE "apps" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"slug" text NOT NULL,
	"name" text NOT NULL,
	"category" text NOT NULL,
	"description" text NOT NULL,
	"live_url" text,
	"custom_domain" text,
	"github_repo" text,
	"hosting" text,
	"stage" text NOT NULL,
	"visible_on_showcase" boolean DEFAULT false NOT NULL,
	"next_move" text,
	"blockers" text,
	"api_dependencies" text[] DEFAULT '{}' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "apps_slug_unique" UNIQUE("slug")
);
CREATE TABLE "status_snapshots" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"app_id" uuid NOT NULL,
	"checked_at" timestamp with time zone DEFAULT now() NOT NULL,
	"url_status" integer,
	"url_response_ms" integer,
	"last_commit_at" timestamp with time zone,
	"last_commit_msg" text,
	"days_since_commit" integer,
	"health_score" text NOT NULL,
	"drift_detected" boolean DEFAULT false NOT NULL
);
ALTER TABLE "status_snapshots" ADD CONSTRAINT "status_snapshots_app_id_apps_id_fk" FOREIGN KEY ("app_id") REFERENCES "public"."apps"("id") ON DELETE cascade ON UPDATE no action;

WITH new_app AS (
  INSERT INTO apps (
    slug, name, category, description, live_url, custom_domain,
    github_repo, hosting, stage, visible_on_showcase, next_move,
    blockers, api_dependencies
  ) VALUES (
    'roof-mri-website', 'Roof MRI Website', 'roofmri', 'Marketing site and PHD Scale reference.',
    'https://roof-mri.com', 'roof-mri.com',
    'adam1capps/roof-mri-main-website', 'netlify', 'mature',
    TRUE, 'Refresh case-study section with Rackley data.',
    NULL, ARRAY['SendGrid', 'Plausible']::text[]
  )
  RETURNING id
)
INSERT INTO status_snapshots (
  app_id, checked_at, url_status, url_response_ms, last_commit_at,
  last_commit_msg, days_since_commit, health_score, drift_detected
)
SELECT
  id, '2026-05-18T08:00:00.000Z'::timestamptz, 200, 184,
  '2026-04-22'::timestamptz, 'copy: tighten PHD Scale callouts',
  26, 'healthy', FALSE
FROM new_app;

WITH new_app AS (
  INSERT INTO apps (
    slug, name, category, description, live_url, custom_domain,
    github_repo, hosting, stage, visible_on_showcase, next_move,
    blockers, api_dependencies
  ) VALUES (
    'proposals-roofmri', 'Proposals App', 'roofmri', 'Generates Rackley moisture-detection proposals from intake form.',
    'https://proposals.roof-mri.com', 'proposals.roof-mri.com',
    'adam1capps/roof-mri-backend', 'netlify+render', 'live',
    TRUE, 'Wire Render service health to status dot.',
    NULL, ARRAY['Anthropic', 'Neon', 'SendGrid', 'Render']::text[]
  )
  RETURNING id
)
INSERT INTO status_snapshots (
  app_id, checked_at, url_status, url_response_ms, last_commit_at,
  last_commit_msg, days_since_commit, health_score, drift_detected
)
SELECT
  id, '2026-05-18T08:00:00.000Z'::timestamptz, 200, 412,
  '2026-05-12'::timestamptz, 'fix: PDF orientation on letter size',
  6, 'healthy', FALSE
FROM new_app;

WITH new_app AS (
  INSERT INTO apps (
    slug, name, category, description, live_url, custom_domain,
    github_repo, hosting, stage, visible_on_showcase, next_move,
    blockers, api_dependencies
  ) VALUES (
    'mri-connect', 'MRI Connect', 'roofmri', 'Contractor portal for certified Rackley installers.',
    'https://connect.roof-mri.com', 'connect.roof-mri.com',
    'adam1capps/roof-mri-connect', 'netlify', 'live',
    TRUE, 'Add @re-dry.com login gate for staff view.',
    NULL, ARRAY['Clerk', 'Neon']::text[]
  )
  RETURNING id
)
INSERT INTO status_snapshots (
  app_id, checked_at, url_status, url_response_ms, last_commit_at,
  last_commit_msg, days_since_commit, health_score, drift_detected
)
SELECT
  id, '2026-05-18T08:00:00.000Z'::timestamptz, 200, 236,
  '2026-05-09'::timestamptz, 'feat: certificate verification endpoint',
  9, 'healthy', FALSE
FROM new_app;

WITH new_app AS (
  INSERT INTO apps (
    slug, name, category, description, live_url, custom_domain,
    github_repo, hosting, stage, visible_on_showcase, next_move,
    blockers, api_dependencies
  ) VALUES (
    'pro-trainers', 'Pro Trainers Presentation', 'roofmri', 'Slide deck site used in PHD certification classes.',
    'https://protraining.roof-mri.com', 'protraining.roof-mri.com',
    'adam1capps/roof-mri-training-presentation-pro', 'netlify', 'live',
    TRUE, 'Replace lesson 4 video with re-recorded version.',
    'Waiting on edited footage from production.', ARRAY[]::text[]
  )
  RETURNING id
)
INSERT INTO status_snapshots (
  app_id, checked_at, url_status, url_response_ms, last_commit_at,
  last_commit_msg, days_since_commit, health_score, drift_detected
)
SELECT
  id, '2026-05-18T08:00:00.000Z'::timestamptz, 200, 198,
  '2026-03-30'::timestamptz, 'content: add lesson 6 slide notes',
  49, 'healthy', FALSE
FROM new_app;

WITH new_app AS (
  INSERT INTO apps (
    slug, name, category, description, live_url, custom_domain,
    github_repo, hosting, stage, visible_on_showcase, next_move,
    blockers, api_dependencies
  ) VALUES (
    'app-guide', 'App Guide', 'roofmri', 'In-product help index for the Roof MRI app suite.',
    'https://appguide.roof-mri.com', 'appguide.roof-mri.com',
    'adam1capps/roof-mri-app-guide', 'netlify', 'live',
    TRUE, 'Index the warranty app''s new screens.',
    NULL, ARRAY[]::text[]
  )
  RETURNING id
)
INSERT INTO status_snapshots (
  app_id, checked_at, url_status, url_response_ms, last_commit_at,
  last_commit_msg, days_since_commit, health_score, drift_detected
)
SELECT
  id, '2026-05-18T08:00:00.000Z'::timestamptz, 200, 152,
  '2026-05-02'::timestamptz, 'docs: vent placement walkthrough',
  16, 'healthy', FALSE
FROM new_app;

WITH new_app AS (
  INSERT INTO apps (
    slug, name, category, description, live_url, custom_domain,
    github_repo, hosting, stage, visible_on_showcase, next_move,
    blockers, api_dependencies
  ) VALUES (
    'certificate-generator', 'Certificate Generator', 'roofmri', 'PHD Scale certificate PDFs for trained contractors.',
    'https://certifications.roof-mri.com', 'certifications.roof-mri.com',
    'adam1capps/mri_certificate_generator', 'netlify', 'live',
    TRUE, 'Pull recipient list from Connect instead of CSV upload.',
    NULL, ARRAY['Neon']::text[]
  )
  RETURNING id
)
INSERT INTO status_snapshots (
  app_id, checked_at, url_status, url_response_ms, last_commit_at,
  last_commit_msg, days_since_commit, health_score, drift_detected
)
SELECT
  id, '2026-05-18T08:00:00.000Z'::timestamptz, 200, 267,
  '2026-04-18'::timestamptz, 'feat: batch download zip',
  30, 'healthy', FALSE
FROM new_app;

WITH new_app AS (
  INSERT INTO apps (
    slug, name, category, description, live_url, custom_domain,
    github_repo, hosting, stage, visible_on_showcase, next_move,
    blockers, api_dependencies
  ) VALUES (
    'rackley-reports', 'Rackley Reports', 'roofmri', 'Customer-facing moisture report viewer for Rackley jobs.',
    'https://rackley.roof-mri.com', 'rackley.roof-mri.com',
    'adam1capps/rackley-roof-mri-reports', 'netlify', 'live',
    TRUE, 'Add per-roof drill-down from index page.',
    NULL, ARRAY['Neon', 'Mapbox']::text[]
  )
  RETURNING id
)
INSERT INTO status_snapshots (
  app_id, checked_at, url_status, url_response_ms, last_commit_at,
  last_commit_msg, days_since_commit, health_score, drift_detected
)
SELECT
  id, '2026-05-18T08:00:00.000Z'::timestamptz, 200, 309,
  '2026-05-15'::timestamptz, 'feat: PDF export with thermal overlay',
  3, 'healthy', FALSE
FROM new_app;

WITH new_app AS (
  INSERT INTO apps (
    slug, name, category, description, live_url, custom_domain,
    github_repo, hosting, stage, visible_on_showcase, next_move,
    blockers, api_dependencies
  ) VALUES (
    'warranty-management', 'Warranty Management App', 'roofmri', 'Warranty claim intake and certified-roof registry.',
    'https://warranty-app-kofu.onrender.com', NULL,
    'adam1capps/warranty-management-app', 'netlify+render', 'live',
    FALSE, 'Move from Render free tier to paid; cold starts hurting UX.',
    NULL, ARRAY['Render', 'Neon', 'SendGrid']::text[]
  )
  RETURNING id
)
INSERT INTO status_snapshots (
  app_id, checked_at, url_status, url_response_ms, last_commit_at,
  last_commit_msg, days_since_commit, health_score, drift_detected
)
SELECT
  id, '2026-05-18T08:00:00.000Z'::timestamptz, 200, 1840,
  '2026-05-07'::timestamptz, 'chore: bump renderer image',
  11, 'healthy', FALSE
FROM new_app;

WITH new_app AS (
  INSERT INTO apps (
    slug, name, category, description, live_url, custom_domain,
    github_repo, hosting, stage, visible_on_showcase, next_move,
    blockers, api_dependencies
  ) VALUES (
    'training-site', 'Training Site', 'roofmri', 'Legacy training portal predating Pro Trainers.',
    'https://training.roof-mri.com', 'training.roof-mri.com',
    NULL, 'netlify (manual)', 'polishing',
    FALSE, 'Decide: redirect to protraining or rehost in a repo.',
    NULL, ARRAY[]::text[]
  )
  RETURNING id
)
INSERT INTO status_snapshots (
  app_id, checked_at, url_status, url_response_ms, last_commit_at,
  last_commit_msg, days_since_commit, health_score, drift_detected
)
SELECT
  id, '2026-05-18T08:00:00.000Z'::timestamptz, 200, 178,
  NULL, NULL,
  NULL, 'warning', TRUE
FROM new_app;

WITH new_app AS (
  INSERT INTO apps (
    slug, name, category, description, live_url, custom_domain,
    github_repo, hosting, stage, visible_on_showcase, next_move,
    blockers, api_dependencies
  ) VALUES (
    'moisture-detection', 'Moisture Detection', 'roofmri', 'Landing for the moisture-detection training program.',
    'https://moisture-detection.roof-mri.com', 'moisture-detection.roof-mri.com',
    NULL, 'netlify (manual)', 'polishing',
    FALSE, 'Move source into a repo; currently only on the Netlify drop.',
    NULL, ARRAY[]::text[]
  )
  RETURNING id
)
INSERT INTO status_snapshots (
  app_id, checked_at, url_status, url_response_ms, last_commit_at,
  last_commit_msg, days_since_commit, health_score, drift_detected
)
SELECT
  id, '2026-05-18T08:00:00.000Z'::timestamptz, 200, 202,
  NULL, NULL,
  NULL, 'warning', TRUE
FROM new_app;

WITH new_app AS (
  INSERT INTO apps (
    slug, name, category, description, live_url, custom_domain,
    github_repo, hosting, stage, visible_on_showcase, next_move,
    blockers, api_dependencies
  ) VALUES (
    'eric-adam-example', 'Eric/Adam Example', 'roofmri', 'Reference build used to walk Eric through the stack.',
    'https://adamericexample.roof-mri.com', 'adamericexample.roof-mri.com',
    'adam1capps/eric-adam-example', 'netlify', 'live',
    FALSE, 'Archive once handoff is signed off.',
    NULL, ARRAY[]::text[]
  )
  RETURNING id
)
INSERT INTO status_snapshots (
  app_id, checked_at, url_status, url_response_ms, last_commit_at,
  last_commit_msg, days_since_commit, health_score, drift_detected
)
SELECT
  id, '2026-05-18T08:00:00.000Z'::timestamptz, 200, 124,
  '2026-02-04'::timestamptz, 'walkthrough: routing example',
  103, 'warning', FALSE
FROM new_app;

WITH new_app AS (
  INSERT INTO apps (
    slug, name, category, description, live_url, custom_domain,
    github_repo, hosting, stage, visible_on_showcase, next_move,
    blockers, api_dependencies
  ) VALUES (
    'redry-website', 'ReDry Website', 'redry', 'Main commercial site for the Rapid-Vent rental program.',
    'https://re-dry.com', 're-dry.com',
    'adam1capps/ReDry-Website', 'netlify', 'mature',
    TRUE, 'New hero copy from the 2026 messaging refresh.',
    NULL, ARRAY['SendGrid', 'Plausible']::text[]
  )
  RETURNING id
)
INSERT INTO status_snapshots (
  app_id, checked_at, url_status, url_response_ms, last_commit_at,
  last_commit_msg, days_since_commit, health_score, drift_detected
)
SELECT
  id, '2026-05-18T08:00:00.000Z'::timestamptz, 200, 165,
  '2026-04-29'::timestamptz, 'content: update fleet count',
  19, 'healthy', FALSE
FROM new_app;

WITH new_app AS (
  INSERT INTO apps (
    slug, name, category, description, live_url, custom_domain,
    github_repo, hosting, stage, visible_on_showcase, next_move,
    blockers, api_dependencies
  ) VALUES (
    'job-lifecycle', 'Job Lifecycle / Job Board', 'redry', 'Internal board tracking every Rapid-Vent rental from intake to return.',
    'https://jobboard.re-dry.com', 'jobboard.re-dry.com',
    'adam1capps/job_lifecycle_app', 'netlify', 'live',
    TRUE, 'Surface days-since-status-change on each card.',
    NULL, ARRAY['Neon', 'Clerk', 'SendGrid']::text[]
  )
  RETURNING id
)
INSERT INTO status_snapshots (
  app_id, checked_at, url_status, url_response_ms, last_commit_at,
  last_commit_msg, days_since_commit, health_score, drift_detected
)
SELECT
  id, '2026-05-18T08:00:00.000Z'::timestamptz, 200, 289,
  '2026-05-14'::timestamptz, 'feat: filter by foreman',
  4, 'healthy', FALSE
FROM new_app;

WITH new_app AS (
  INSERT INTO apps (
    slug, name, category, description, live_url, custom_domain,
    github_repo, hosting, stage, visible_on_showcase, next_move,
    blockers, api_dependencies
  ) VALUES (
    'flyby', 'Flyby (3D)', 'redry', 'Three.js flyby of a wet roof showing dry-down progression.',
    'https://flyby.re-dry.com', 'flyby.re-dry.com',
    'adam1capps/flyby-redry', 'netlify', 'live',
    TRUE, 'Bake camera path for the new sales pitch.',
    NULL, ARRAY[]::text[]
  )
  RETURNING id
)
INSERT INTO status_snapshots (
  app_id, checked_at, url_status, url_response_ms, last_commit_at,
  last_commit_msg, days_since_commit, health_score, drift_detected
)
SELECT
  id, '2026-05-18T08:00:00.000Z'::timestamptz, 200, 421,
  '2026-05-06'::timestamptz, 'feat: time-of-day toggle',
  12, 'healthy', FALSE
FROM new_app;

WITH new_app AS (
  INSERT INTO apps (
    slug, name, category, description, live_url, custom_domain,
    github_repo, hosting, stage, visible_on_showcase, next_move,
    blockers, api_dependencies
  ) VALUES (
    'vent-placement', 'Vent Placement', 'redry', 'Web app for laying out Rapid-Vents on a roof plan.',
    'https://vents.re-dry.com', 'vents.re-dry.com',
    'adam1capps/redry-vent-placement', 'netlify+render', 'live',
    TRUE, 'Contractor read-only view with PHD-scale overlay.',
    NULL, ARRAY['Neon', 'Anthropic', 'Render']::text[]
  )
  RETURNING id
)
INSERT INTO status_snapshots (
  app_id, checked_at, url_status, url_response_ms, last_commit_at,
  last_commit_msg, days_since_commit, health_score, drift_detected
)
SELECT
  id, '2026-05-18T08:00:00.000Z'::timestamptz, 200, 312,
  '2026-05-16'::timestamptz, 'feat: address > roof > project tree',
  2, 'healthy', FALSE
FROM new_app;

WITH new_app AS (
  INSERT INTO apps (
    slug, name, category, description, live_url, custom_domain,
    github_repo, hosting, stage, visible_on_showcase, next_move,
    blockers, api_dependencies
  ) VALUES (
    'accounting', 'Accounting Software', 'redry', 'Internal-only accounting workspace; replaces QBO export hacks.',
    'https://redry-accounting-app.netlify.app', NULL,
    'adam1capps/accounting-software', 'netlify', 'mvp',
    FALSE, 'Map chart of accounts to the new categories.',
    'Waiting on bookkeeper signoff for category list.', ARRAY['Neon', 'Plaid']::text[]
  )
  RETURNING id
)
INSERT INTO status_snapshots (
  app_id, checked_at, url_status, url_response_ms, last_commit_at,
  last_commit_msg, days_since_commit, health_score, drift_detected
)
SELECT
  id, '2026-05-18T08:00:00.000Z'::timestamptz, 200, 341,
  '2026-05-10'::timestamptz, 'feat: invoice import',
  8, 'healthy', FALSE
FROM new_app;

WITH new_app AS (
  INSERT INTO apps (
    slug, name, category, description, live_url, custom_domain,
    github_repo, hosting, stage, visible_on_showcase, next_move,
    blockers, api_dependencies
  ) VALUES (
    'proposal-builder', 'Proposal Builder', 'redry', 'Render-only service that compiles Rapid-Vent proposals from job data.',
    NULL, NULL,
    'adam1capps/redry-proposal-app', 'render', 'mvp',
    FALSE, 'Front-end shell; service runs but has no UI.',
    NULL, ARRAY['Render', 'Anthropic']::text[]
  )
  RETURNING id
)
INSERT INTO status_snapshots (
  app_id, checked_at, url_status, url_response_ms, last_commit_at,
  last_commit_msg, days_since_commit, health_score, drift_detected
)
SELECT
  id, '2026-05-18T08:00:00.000Z'::timestamptz, NULL, NULL,
  '2026-04-26'::timestamptz, 'feat: scope-of-work generator',
  22, 'warning', FALSE
FROM new_app;

WITH new_app AS (
  INSERT INTO apps (
    slug, name, category, description, live_url, custom_domain,
    github_repo, hosting, stage, visible_on_showcase, next_move,
    blockers, api_dependencies
  ) VALUES (
    'invoice-manager', 'Invoice Manager', 'redry', 'One-off invoice viewer for rental accounts.',
    'https://invoice.re-dry.com', 'invoice.re-dry.com',
    'adam1capps/invoice-manager', 'netlify (manual)', 'polishing',
    FALSE, 'Reconcile with the new Accounting app; likely deprecate.',
    NULL, ARRAY[]::text[]
  )
  RETURNING id
)
INSERT INTO status_snapshots (
  app_id, checked_at, url_status, url_response_ms, last_commit_at,
  last_commit_msg, days_since_commit, health_score, drift_detected
)
SELECT
  id, '2026-05-18T08:00:00.000Z'::timestamptz, 500, 1240,
  '2025-11-04'::timestamptz, 'fix: stripe webhook idempotency',
  195, 'broken', FALSE
FROM new_app;

WITH new_app AS (
  INSERT INTO apps (
    slug, name, category, description, live_url, custom_domain,
    github_repo, hosting, stage, visible_on_showcase, next_move,
    blockers, api_dependencies
  ) VALUES (
    'redry-links', 'ReDry Links', 'redry', 'Short-link hub used in printed material.',
    'https://redry-links.netlify.app', NULL,
    NULL, 'netlify (manual)', 'live',
    FALSE, 'Move to a repo so deploys aren''t drag-and-drop.',
    NULL, ARRAY[]::text[]
  )
  RETURNING id
)
INSERT INTO status_snapshots (
  app_id, checked_at, url_status, url_response_ms, last_commit_at,
  last_commit_msg, days_since_commit, health_score, drift_detected
)
SELECT
  id, '2026-05-18T08:00:00.000Z'::timestamptz, 200, 118,
  NULL, NULL,
  NULL, 'warning', TRUE
FROM new_app;

WITH new_app AS (
  INSERT INTO apps (
    slug, name, category, description, live_url, custom_domain,
    github_repo, hosting, stage, visible_on_showcase, next_move,
    blockers, api_dependencies
  ) VALUES (
    'li-outreach', 'LinkedIn Outreach', 'redry', 'Lead-gen target list and message templates for ReDry sales.',
    'https://redry-li-outreach.netlify.app', NULL,
    NULL, 'netlify (manual)', 'live',
    FALSE, 'Repo it; pair with the LinkedIn App for sending.',
    NULL, ARRAY[]::text[]
  )
  RETURNING id
)
INSERT INTO status_snapshots (
  app_id, checked_at, url_status, url_response_ms, last_commit_at,
  last_commit_msg, days_since_commit, health_score, drift_detected
)
SELECT
  id, '2026-05-18T08:00:00.000Z'::timestamptz, 200, 142,
  NULL, NULL,
  NULL, 'warning', TRUE
FROM new_app;

WITH new_app AS (
  INSERT INTO apps (
    slug, name, category, description, live_url, custom_domain,
    github_repo, hosting, stage, visible_on_showcase, next_move,
    blockers, api_dependencies
  ) VALUES (
    'internship-2026', '2026 Internship', 'redry', 'Recruiting page for the 2026 ReDry field internship.',
    'https://redry-2026-internship.netlify.app', NULL,
    NULL, 'netlify (manual)', 'live',
    FALSE, 'Add custom domain once we choose redry.jobs or careers.re-dry.com.',
    NULL, ARRAY['SendGrid']::text[]
  )
  RETURNING id
)
INSERT INTO status_snapshots (
  app_id, checked_at, url_status, url_response_ms, last_commit_at,
  last_commit_msg, days_since_commit, health_score, drift_detected
)
SELECT
  id, '2026-05-18T08:00:00.000Z'::timestamptz, 200, 171,
  NULL, NULL,
  NULL, 'warning', TRUE
FROM new_app;

WITH new_app AS (
  INSERT INTO apps (
    slug, name, category, description, live_url, custom_domain,
    github_repo, hosting, stage, visible_on_showcase, next_move,
    blockers, api_dependencies
  ) VALUES (
    'mindreadir-press', 'MindReadir Press Engine', 'mindreadir', 'Press-release engine for MindReadir announcements.',
    'https://mindreadir.com', 'mindreadir.com',
    'adam1capps/mindreadir-press-app', 'netlify+render', 'live',
    TRUE, 'Move LLM calls from Render worker to direct fetch.',
    NULL, ARRAY['Anthropic', 'Render', 'Neon', 'SendGrid']::text[]
  )
  RETURNING id
)
INSERT INTO status_snapshots (
  app_id, checked_at, url_status, url_response_ms, last_commit_at,
  last_commit_msg, days_since_commit, health_score, drift_detected
)
SELECT
  id, '2026-05-18T08:00:00.000Z'::timestamptz, 200, 498,
  '2026-05-11'::timestamptz, 'feat: outlet targeting',
  7, 'healthy', FALSE
FROM new_app;

WITH new_app AS (
  INSERT INTO apps (
    slug, name, category, description, live_url, custom_domain,
    github_repo, hosting, stage, visible_on_showcase, next_move,
    blockers, api_dependencies
  ) VALUES (
    'lightup', 'LightUp Proposal', 'cappsapps', 'Consulting proposal landing page for the LightUp engagement.',
    'https://cappsapps.ai/lightup', 'cappsapps.ai',
    'adam1capps/lightup', 'netlify', 'live',
    TRUE, 'Add scope-extension addendum section.',
    NULL, ARRAY[]::text[]
  )
  RETURNING id
)
INSERT INTO status_snapshots (
  app_id, checked_at, url_status, url_response_ms, last_commit_at,
  last_commit_msg, days_since_commit, health_score, drift_detected
)
SELECT
  id, '2026-05-18T08:00:00.000Z'::timestamptz, 200, 108,
  '2026-05-08'::timestamptz, 'copy: tighten deliverables list',
  10, 'healthy', FALSE
FROM new_app;

WITH new_app AS (
  INSERT INTO apps (
    slug, name, category, description, live_url, custom_domain,
    github_repo, hosting, stage, visible_on_showcase, next_move,
    blockers, api_dependencies
  ) VALUES (
    'cappsapps-proposals', 'Capps Apps Proposals', 'cappsapps', 'Template engine for new Capps Apps consulting proposals.',
    NULL, NULL,
    'adam1capps/cappsapps-proposals', 'none', 'building',
    FALSE, 'Pick a template structure and lock the first three sections.',
    NULL, ARRAY['Anthropic']::text[]
  )
  RETURNING id
)
INSERT INTO status_snapshots (
  app_id, checked_at, url_status, url_response_ms, last_commit_at,
  last_commit_msg, days_since_commit, health_score, drift_detected
)
SELECT
  id, '2026-05-18T08:00:00.000Z'::timestamptz, NULL, NULL,
  '2026-02-19'::timestamptz, 'scaffold: route shell',
  88, 'stale', FALSE
FROM new_app;

WITH new_app AS (
  INSERT INTO apps (
    slug, name, category, description, live_url, custom_domain,
    github_repo, hosting, stage, visible_on_showcase, next_move,
    blockers, api_dependencies
  ) VALUES (
    'hub-app', 'The Hub App', 'internal', 'Internal dispatcher used to route inbound work to the right portfolio app.',
    'https://thehubapp.netlify.app', NULL,
    'adam1capps/hub-dispatch', 'netlify', 'live',
    FALSE, 'Roll into this Command Center.',
    NULL, ARRAY['Neon']::text[]
  )
  RETURNING id
)
INSERT INTO status_snapshots (
  app_id, checked_at, url_status, url_response_ms, last_commit_at,
  last_commit_msg, days_since_commit, health_score, drift_detected
)
SELECT
  id, '2026-05-18T08:00:00.000Z'::timestamptz, 200, 204,
  '2026-04-11'::timestamptz, 'feat: routing rule editor',
  37, 'healthy', FALSE
FROM new_app;

WITH new_app AS (
  INSERT INTO apps (
    slug, name, category, description, live_url, custom_domain,
    github_repo, hosting, stage, visible_on_showcase, next_move,
    blockers, api_dependencies
  ) VALUES (
    'hub-app-scanner', 'Hub App Scanner', 'internal', 'launchd job that walks the local code directory and reports orphan repos.',
    NULL, NULL,
    'adam1capps/hub-app-scanner', 'local', 'live',
    FALSE, 'Push results to Neon so the Command Center can read them.',
    NULL, ARRAY['Neon']::text[]
  )
  RETURNING id
)
INSERT INTO status_snapshots (
  app_id, checked_at, url_status, url_response_ms, last_commit_at,
  last_commit_msg, days_since_commit, health_score, drift_detected
)
SELECT
  id, '2026-05-18T08:00:00.000Z'::timestamptz, NULL, NULL,
  '2026-05-13'::timestamptz, 'feat: detect netlify-only deploys',
  5, 'warning', FALSE
FROM new_app;

WITH new_app AS (
  INSERT INTO apps (
    slug, name, category, description, live_url, custom_domain,
    github_repo, hosting, stage, visible_on_showcase, next_move,
    blockers, api_dependencies
  ) VALUES (
    'taskline', 'TaskLine App', 'internal', 'Personal task line; minimal, single-stream.',
    NULL, NULL,
    'adam1capps/taskline-app', 'none', 'building',
    FALSE, 'Decide if this stays personal or becomes a portfolio app.',
    NULL, ARRAY[]::text[]
  )
  RETURNING id
)
INSERT INTO status_snapshots (
  app_id, checked_at, url_status, url_response_ms, last_commit_at,
  last_commit_msg, days_since_commit, health_score, drift_detected
)
SELECT
  id, '2026-05-18T08:00:00.000Z'::timestamptz, NULL, NULL,
  '2026-01-21'::timestamptz, 'init: schema sketch',
  117, 'stale', FALSE
FROM new_app;

WITH new_app AS (
  INSERT INTO apps (
    slug, name, category, description, live_url, custom_domain,
    github_repo, hosting, stage, visible_on_showcase, next_move,
    blockers, api_dependencies
  ) VALUES (
    'smart-bookkeeper', 'Smart Bookkeeper', 'internal', 'Categorization layer over Plaid transactions for the ReDry books.',
    NULL, NULL,
    'adam1capps/smart-bookkeeper', 'none', 'building',
    FALSE, 'Fold into the ReDry Accounting app.',
    NULL, ARRAY['Plaid', 'Anthropic']::text[]
  )
  RETURNING id
)
INSERT INTO status_snapshots (
  app_id, checked_at, url_status, url_response_ms, last_commit_at,
  last_commit_msg, days_since_commit, health_score, drift_detected
)
SELECT
  id, '2026-05-18T08:00:00.000Z'::timestamptz, NULL, NULL,
  '2026-03-02'::timestamptz, 'feat: rule engine prototype',
  77, 'stale', FALSE
FROM new_app;

WITH new_app AS (
  INSERT INTO apps (
    slug, name, category, description, live_url, custom_domain,
    github_repo, hosting, stage, visible_on_showcase, next_move,
    blockers, api_dependencies
  ) VALUES (
    'linkedin-app', 'LinkedIn App', 'internal', 'Sender service paired with the ReDry outreach target list.',
    NULL, NULL,
    'adam1capps/linkedin-app', 'none', 'building',
    FALSE, 'Stalled. Pick up after LinkedIn API approval lands.',
    'Awaiting LinkedIn Marketing Developer Platform access.', ARRAY['LinkedIn']::text[]
  )
  RETURNING id
)
INSERT INTO status_snapshots (
  app_id, checked_at, url_status, url_response_ms, last_commit_at,
  last_commit_msg, days_since_commit, health_score, drift_detected
)
SELECT
  id, '2026-05-18T08:00:00.000Z'::timestamptz, NULL, NULL,
  '2026-02-28'::timestamptz, 'scaffold: auth flow',
  79, 'stale', FALSE
FROM new_app;

WITH new_app AS (
  INSERT INTO apps (
    slug, name, category, description, live_url, custom_domain,
    github_repo, hosting, stage, visible_on_showcase, next_move,
    blockers, api_dependencies
  ) VALUES (
    'gravimetric-readings', 'Gravimetric Readings App', 'internal', 'Logbook for lab gravimetric moisture readings used to calibrate PHD Scale.',
    'https://gravimetrics-app.netlify.app', NULL,
    'adam1capps/gravimetric-readings-app', 'netlify+render', 'mvp',
    FALSE, 'Add CSV import from the lab''s USB scale.',
    NULL, ARRAY['Render', 'Neon']::text[]
  )
  RETURNING id
)
INSERT INTO status_snapshots (
  app_id, checked_at, url_status, url_response_ms, last_commit_at,
  last_commit_msg, days_since_commit, health_score, drift_detected
)
SELECT
  id, '2026-05-18T08:00:00.000Z'::timestamptz, 200, 367,
  '2026-04-04'::timestamptz, 'feat: reading entry form',
  44, 'healthy', FALSE
FROM new_app;

WITH new_app AS (
  INSERT INTO apps (
    slug, name, category, description, live_url, custom_domain,
    github_repo, hosting, stage, visible_on_showcase, next_move,
    blockers, api_dependencies
  ) VALUES (
    'grid-report', 'Grid & Report Workflow', 'internal', 'Internal grid editor and report renderer used for ad-hoc QA.',
    'https://helpful-seahorse-755ba9.netlify.app', NULL,
    'adam1capps/grid-and-report-workflow', 'netlify', 'mvp',
    FALSE, 'Give it a custom domain or sunset.',
    NULL, ARRAY[]::text[]
  )
  RETURNING id
)
INSERT INTO status_snapshots (
  app_id, checked_at, url_status, url_response_ms, last_commit_at,
  last_commit_msg, days_since_commit, health_score, drift_detected
)
SELECT
  id, '2026-05-18T08:00:00.000Z'::timestamptz, 404, 96,
  '2026-03-19'::timestamptz, 'feat: report renderer v2',
  60, 'broken', FALSE
FROM new_app;

WITH new_app AS (
  INSERT INTO apps (
    slug, name, category, description, live_url, custom_domain,
    github_repo, hosting, stage, visible_on_showcase, next_move,
    blockers, api_dependencies
  ) VALUES (
    'truhome', 'TruHome Experience', 'internal', 'Client-specific landing experience for the TruHome pilot.',
    'https://truhome-experience.netlify.app', NULL,
    'adam1capps/truhomeexperience', 'netlify', 'mvp',
    FALSE, 'Decide whether TruHome continues; if not, archive.',
    NULL, ARRAY[]::text[]
  )
  RETURNING id
)
INSERT INTO status_snapshots (
  app_id, checked_at, url_status, url_response_ms, last_commit_at,
  last_commit_msg, days_since_commit, health_score, drift_detected
)
SELECT
  id, '2026-05-18T08:00:00.000Z'::timestamptz, 200, 221,
  '2026-02-12'::timestamptz, 'feat: walkthrough video block',
  95, 'warning', FALSE
FROM new_app;

WITH new_app AS (
  INSERT INTO apps (
    slug, name, category, description, live_url, custom_domain,
    github_repo, hosting, stage, visible_on_showcase, next_move,
    blockers, api_dependencies
  ) VALUES (
    'roof-mri-website-stub', 'roof-mri-website (empty)', 'roofmri', 'Empty stub repo. Superseded by roof-mri-main-website.',
    NULL, NULL,
    'adam1capps/roof-mri-website', 'none', 'archive',
    FALSE, NULL,
    NULL, ARRAY[]::text[]
  )
  RETURNING id
)
INSERT INTO status_snapshots (
  app_id, checked_at, url_status, url_response_ms, last_commit_at,
  last_commit_msg, days_since_commit, health_score, drift_detected
)
SELECT
  id, '2026-05-18T08:00:00.000Z'::timestamptz, NULL, NULL,
  '2025-04-02'::timestamptz, 'init',
  411, 'archive', FALSE
FROM new_app;

WITH new_app AS (
  INSERT INTO apps (
    slug, name, category, description, live_url, custom_domain,
    github_repo, hosting, stage, visible_on_showcase, next_move,
    blockers, api_dependencies
  ) VALUES (
    'roof-mri-frontend', 'roof-mri-frontend (stub)', 'roofmri', 'Empty stub repo. No live deploy.',
    NULL, NULL,
    'adam1capps/roof-mri-frontend', 'none', 'archive',
    FALSE, NULL,
    NULL, ARRAY[]::text[]
  )
  RETURNING id
)
INSERT INTO status_snapshots (
  app_id, checked_at, url_status, url_response_ms, last_commit_at,
  last_commit_msg, days_since_commit, health_score, drift_detected
)
SELECT
  id, '2026-05-18T08:00:00.000Z'::timestamptz, NULL, NULL,
  '2025-05-18'::timestamptz, 'init',
  365, 'archive', FALSE
FROM new_app;

WITH new_app AS (
  INSERT INTO apps (
    slug, name, category, description, live_url, custom_domain,
    github_repo, hosting, stage, visible_on_showcase, next_move,
    blockers, api_dependencies
  ) VALUES (
    'roofwarrantymanagement', 'roofwarrantymanagement (readme)', 'roofmri', 'README only. Superseded by warranty-management-app.',
    NULL, NULL,
    'adam1capps/roofwarrantymanagement', 'none', 'archive',
    FALSE, NULL,
    NULL, ARRAY[]::text[]
  )
  RETURNING id
)
INSERT INTO status_snapshots (
  app_id, checked_at, url_status, url_response_ms, last_commit_at,
  last_commit_msg, days_since_commit, health_score, drift_detected
)
SELECT
  id, '2026-05-18T08:00:00.000Z'::timestamptz, NULL, NULL,
  '2025-07-30'::timestamptz, 'init README',
  292, 'archive', FALSE
FROM new_app;

WITH new_app AS (
  INSERT INTO apps (
    slug, name, category, description, live_url, custom_domain,
    github_repo, hosting, stage, visible_on_showcase, next_move,
    blockers, api_dependencies
  ) VALUES (
    'redry-website-dup', 'redry-website-03042026 (dup)', 'redry', 'Working-copy duplicate of ReDry-Website. Safe to archive.',
    NULL, NULL,
    'adam1capps/redry-website-03042026', 'none', 'archive',
    FALSE, NULL,
    NULL, ARRAY[]::text[]
  )
  RETURNING id
)
INSERT INTO status_snapshots (
  app_id, checked_at, url_status, url_response_ms, last_commit_at,
  last_commit_msg, days_since_commit, health_score, drift_detected
)
SELECT
  id, '2026-05-18T08:00:00.000Z'::timestamptz, NULL, NULL,
  '2026-03-04'::timestamptz, 'backup snapshot',
  75, 'archive', FALSE
FROM new_app;

WITH new_app AS (
  INSERT INTO apps (
    slug, name, category, description, live_url, custom_domain,
    github_repo, hosting, stage, visible_on_showcase, next_move,
    blockers, api_dependencies
  ) VALUES (
    'personal-brand', 'personal-brand (readme)', 'cappsapps', 'README only. Placeholder for a future personal site.',
    NULL, NULL,
    'adam1capps/personal-brand', 'none', 'archive',
    FALSE, NULL,
    NULL, ARRAY[]::text[]
  )
  RETURNING id
)
INSERT INTO status_snapshots (
  app_id, checked_at, url_status, url_response_ms, last_commit_at,
  last_commit_msg, days_since_commit, health_score, drift_detected
)
SELECT
  id, '2026-05-18T08:00:00.000Z'::timestamptz, NULL, NULL,
  '2025-09-11'::timestamptz, 'init',
  249, 'archive', FALSE
FROM new_app;

COMMIT;

-- Verification
SELECT count(*) AS apps_count FROM apps;
SELECT count(*) AS snapshots_count FROM status_snapshots;
SELECT a.slug, s.health_score FROM apps a JOIN status_snapshots s ON s.app_id = a.id WHERE a.slug = 'invoice-manager';
