-- Capps Apps Command Center - Phase 9 notes table + seed bundle.
-- Generated by db/dump-notes-sql.ts. Apply once in the Neon SQL Editor.

BEGIN;

CREATE TABLE "notes" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"app_id" uuid NOT NULL,
	"kind" text NOT NULL,
	"title" text DEFAULT '' NOT NULL,
	"body" text DEFAULT '' NOT NULL,
	"source" text DEFAULT 'manual' NOT NULL,
	"repo_path" text,
	"commit_sha" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by_email" text,
	CONSTRAINT "notes_kind_check" CHECK ("notes"."kind" in ('instruction', 'note'))
);
ALTER TABLE "notes" ADD CONSTRAINT "notes_app_id_apps_id_fk" FOREIGN KEY ("app_id") REFERENCES "public"."apps"("id") ON DELETE cascade ON UPDATE no action;

INSERT INTO notes (
  app_id, kind, title, body, source, repo_path, commit_sha,
  created_at, updated_at
)
SELECT
  a.id, 'instruction', 'Use the theme tokens', 'Pull colors/fonts from `frontend/src/constants/theme.js`. SEG_COLORS controls the wall rotation - don''t redefine it elsewhere. DM Sans only, 6px radii, navy header.', 'claude-md',
  '.cappshub/instructions.md', 'a91f2c4', '2026-05-09T14:00:00Z'::timestamptz, '2026-05-09T14:00:00Z'::timestamptz
FROM apps a WHERE a.slug = 'vent-placement';

INSERT INTO notes (
  app_id, kind, title, body, source, repo_path, commit_sha,
  created_at, updated_at
)
SELECT
  a.id, 'note', 'Render cold-start measurement', 'Stopwatch on the Render service: 2.8s first request after 15min idle. After warmup, 280-340ms steady state. If we move proposal generation here, warm with a /healthz ping every 10min.', 'hook',
  '.cappshub/notes/2026-05-15-render-cold-start.md', 'd4e8a17', '2026-05-15T09:20:00Z'::timestamptz, '2026-05-15T09:20:00Z'::timestamptz
FROM apps a WHERE a.slug = 'vent-placement';

INSERT INTO notes (
  app_id, kind, title, body, source, repo_path, commit_sha,
  created_at, updated_at
)
SELECT
  a.id, 'instruction', 'Contractor view = read-only', 'Contractors must never be able to edit vent placement. The PHD-scale overlay should render but actions are disabled.', 'claude-md',
  '.cappshub/instructions.md', 'a91f2c4', '2026-05-11T08:10:00Z'::timestamptz, '2026-05-11T08:10:00Z'::timestamptz
FROM apps a WHERE a.slug = 'vent-placement';

INSERT INTO notes (
  app_id, kind, title, body, source, repo_path, commit_sha,
  created_at, updated_at
)
SELECT
  a.id, 'instruction', 'Foreman filter respects job timezone', 'All filters use the job site timezone, not the foreman''s local. There was a bug where MST/CST jobs got mis-bucketed in the ''today'' filter.', 'slash-command',
  '.cappshub/instructions.md', '7c2b119', '2026-05-12T17:45:00Z'::timestamptz, '2026-05-12T17:45:00Z'::timestamptz
FROM apps a WHERE a.slug = 'job-lifecycle';

INSERT INTO notes (
  app_id, kind, title, body, source, repo_path, commit_sha,
  created_at, updated_at
)
SELECT
  a.id, 'note', 'Status-change-age request', 'Brandon asked: surface how long a job has been in its current status. Want a soft yellow tint when > 5 days.', 'manual',
  NULL, NULL, '2026-05-14T11:00:00Z'::timestamptz, '2026-05-14T11:00:00Z'::timestamptz
FROM apps a WHERE a.slug = 'job-lifecycle';

INSERT INTO notes (
  app_id, kind, title, body, source, repo_path, commit_sha,
  created_at, updated_at
)
SELECT
  a.id, 'note', 'Render free tier - moving off', '1.84s response logged in last poll. That''s cold start. Bumping to paid Render service before the next contractor batch ships next Tuesday.', 'hook',
  '.cappshub/notes/2026-05-16-render-tier.md', 'b1d44a0', '2026-05-16T19:30:00Z'::timestamptz, '2026-05-16T19:30:00Z'::timestamptz
FROM apps a WHERE a.slug = 'warranty-management';

INSERT INTO notes (
  app_id, kind, title, body, source, repo_path, commit_sha,
  created_at, updated_at
)
SELECT
  a.id, 'instruction', 'Voice rules - REDRY_BRAND.md', 'No em dashes. No emoji. Imperative voice. Imperial units. Phone format: 877.733.7973 (dots, not dashes). Domain: re-dry.com (hyphenated).', 'claude-md',
  '.cappshub/instructions.md', 'e0a9c12', '2026-04-29T16:00:00Z'::timestamptz, '2026-04-29T16:00:00Z'::timestamptz
FROM apps a WHERE a.slug = 'redry-website';

INSERT INTO notes (
  app_id, kind, title, body, source, repo_path, commit_sha,
  created_at, updated_at
)
SELECT
  a.id, 'note', '500s started last Friday', 'Stripe webhook signature mismatch after they rotated keys. Quick fix is to pull the new secret from Stripe dashboard. Probably easier to just deprecate this and route invoicing through the new Accounting app.', 'slash-command',
  '.cappshub/notes/2026-05-16-stripe-500s.md', '3f8e0b2', '2026-05-16T08:00:00Z'::timestamptz, '2026-05-16T08:00:00Z'::timestamptz
FROM apps a WHERE a.slug = 'invoice-manager';

INSERT INTO notes (
  app_id, kind, title, body, source, repo_path, commit_sha,
  created_at, updated_at
)
SELECT
  a.id, 'instruction', 'Cert verification endpoint stays public', '/api/verify/:cert_id must remain unauthenticated - it''s hit from QR codes on printed certificates. Rate-limit but never gate.', 'claude-md',
  '.cappshub/instructions.md', '5c1aa83', '2026-05-09T10:00:00Z'::timestamptz, '2026-05-09T10:00:00Z'::timestamptz
FROM apps a WHERE a.slug = 'mri-connect';

INSERT INTO notes (
  app_id, kind, title, body, source, repo_path, commit_sha,
  created_at, updated_at
)
SELECT
  a.id, 'note', 'Anthropic rate-limit playbook', 'Press generation can burst 6-8 calls in a few seconds when an outlet batch ships. If we start hitting 429s, fall back to Render worker with a backoff queue.', 'hook',
  '.cappshub/notes/2026-05-11-anthropic-429.md', '9a2c4d5', '2026-05-11T12:00:00Z'::timestamptz, '2026-05-11T12:00:00Z'::timestamptz
FROM apps a WHERE a.slug = 'mindreadir-press';

COMMIT;

-- Verification
SELECT count(*) AS notes_count FROM notes;  -- expect 10
SELECT a.slug, count(n.*) FROM apps a JOIN notes n ON n.app_id = a.id GROUP BY a.slug ORDER BY a.slug;
