// One-shot: generate the Phase 9 Neon bundle (notes table + seed).
// Run: pnpm tsx db/dump-notes-sql.ts > db/bundle-0002.sql
// Then paste the result into Neon's SQL Editor.

import { readFileSync } from "node:fs";
import { join } from "node:path";

import { NOTE_SEED } from "./seed-notes";

const Q = (v: string | null | undefined): string =>
  v == null ? "NULL" : `'${v.replace(/'/g, "''")}'`;
const Ts = (iso: string): string => `'${iso}'::timestamptz`;

function main() {
  const out: string[] = [];
  out.push("-- Capps Apps Command Center - Phase 9 notes table + seed bundle.");
  out.push("-- Generated by db/dump-notes-sql.ts. Apply once in the Neon SQL Editor.");
  out.push("");
  out.push("BEGIN;");
  out.push("");

  const migration = readFileSync(
    join(process.cwd(), "db", "migrations", "0002_curly_tattoo.sql"),
    "utf-8",
  );
  for (const stmt of migration.split("--> statement-breakpoint")) {
    const trimmed = stmt.trim();
    if (trimmed) out.push(trimmed + (trimmed.endsWith(";") ? "" : ";"));
  }
  out.push("");

  for (const n of NOTE_SEED) {
    out.push(
      [
        "INSERT INTO notes (",
        "  app_id, kind, title, body, source, repo_path, commit_sha,",
        "  created_at, updated_at",
        ")",
        "SELECT",
        `  a.id, ${Q(n.kind)}, ${Q(n.title)}, ${Q(n.body)}, ${Q(n.source)},`,
        `  ${Q(n.repoPath)}, ${Q(n.commitSha)}, ${Ts(n.createdAt)}, ${Ts(n.createdAt)}`,
        `FROM apps a WHERE a.slug = ${Q(n.slug)};`,
        "",
      ].join("\n"),
    );
  }

  out.push("COMMIT;");
  out.push("");
  out.push("-- Verification");
  out.push("SELECT count(*) AS notes_count FROM notes;  -- expect 10");
  out.push(
    "SELECT a.slug, count(n.*) FROM apps a JOIN notes n ON n.app_id = a.id GROUP BY a.slug ORDER BY a.slug;",
  );

  process.stdout.write(out.join("\n") + "\n");
}

main();
