// One-shot: generate a self-contained SQL bundle (migration + seed) for Neon.
// Run: pnpm tsx db/dump-seed-sql.ts > db/bundle-seed.sql
// Then paste the SQL bundle into Neon's SQL Editor.

import { readFileSync } from "node:fs";
import { join } from "node:path";

import { APPS } from "./seed-data";
import { deriveSnapshot } from "../lib/derive";

const Q = (v: string | null | undefined): string =>
  v == null ? "NULL" : `'${v.replace(/'/g, "''")}'`;

const QArr = (arr: readonly string[]): string =>
  `ARRAY[${arr.map(Q).join(", ")}]::text[]`;

const B = (v: boolean): string => (v ? "TRUE" : "FALSE");

const Int = (v: number | null | undefined): string =>
  v == null ? "NULL" : String(v);

const Ts = (iso: string | null | undefined): string =>
  iso == null ? "NULL" : `'${iso}'::timestamptz`;

function main() {
  const out: string[] = [];

  out.push("-- Capps Apps Command Center · Phase 2 migration + seed bundle");
  out.push("-- Generated by db/dump-seed-sql.ts. Idempotent.");
  out.push("");
  out.push("BEGIN;");
  out.push("");

  // Migration (drop-and-create to be re-runnable).
  out.push("DROP TABLE IF EXISTS status_snapshots CASCADE;");
  out.push("DROP TABLE IF EXISTS apps CASCADE;");
  out.push("");
  const migration = readFileSync(
    join(process.cwd(), "db", "migrations", "0000_uneven_snowbird.sql"),
    "utf-8",
  );
  for (const stmt of migration.split("--> statement-breakpoint")) {
    const trimmed = stmt.trim();
    if (trimmed) out.push(trimmed + (trimmed.endsWith(";") ? "" : ";"));
  }
  out.push("");

  // Seed.
  for (const app of APPS) {
    const derived = deriveSnapshot({
      stage: app.stage,
      liveUrl: app.liveUrl,
      githubRepo: app.githubRepo,
      snap: app.snap,
    });

    out.push(
      [
        "WITH new_app AS (",
        "  INSERT INTO apps (",
        "    slug, name, category, description, live_url, custom_domain,",
        "    github_repo, hosting, stage, visible_on_showcase, next_move,",
        "    blockers, api_dependencies",
        "  ) VALUES (",
        `    ${Q(app.slug)}, ${Q(app.name)}, ${Q(app.category)}, ${Q(app.description)},`,
        `    ${Q(app.liveUrl)}, ${Q(app.customDomain)},`,
        `    ${Q(app.githubRepo)}, ${Q(app.hosting)}, ${Q(app.stage)},`,
        `    ${B(app.visibleOnShowcase)}, ${Q(app.nextMove)},`,
        `    ${Q(app.blockers)}, ${QArr(app.apiDependencies)}`,
        "  )",
        "  RETURNING id",
        ")",
        "INSERT INTO status_snapshots (",
        "  app_id, checked_at, url_status, url_response_ms, last_commit_at,",
        "  last_commit_msg, days_since_commit, health_score, drift_detected",
        ")",
        "SELECT",
        `  id, ${Ts(derived.checkedAt)}, ${Int(derived.urlStatus)}, ${Int(derived.urlResponseMs)},`,
        `  ${Ts(derived.lastCommitAt)}, ${Q(derived.lastCommitMsg)},`,
        `  ${Int(derived.daysSinceCommit)}, ${Q(derived.healthScore)}, ${B(derived.driftDetected)}`,
        "FROM new_app;",
        "",
      ].join("\n"),
    );
  }

  out.push("COMMIT;");
  out.push("");
  out.push("-- Verification");
  out.push("SELECT count(*) AS apps_count FROM apps;");
  out.push("SELECT count(*) AS snapshots_count FROM status_snapshots;");
  out.push(
    "SELECT a.slug, s.health_score FROM apps a JOIN status_snapshots s ON s.app_id = a.id WHERE a.slug = 'invoice-manager';",
  );

  process.stdout.write(out.join("\n") + "\n");
}

main();
