// Seed data for Capps Apps Command Center.
// Ported verbatim from prototype/data.js:30-397. 37 apps.
// Treat as immutable seed contract — re-derive from prototype, do not edit by hand.

import type { Category, Stage } from "@/lib/tokens";
import type { SnapshotInput } from "@/lib/derive";

export interface SeedApp {
  name: string;
  slug: string;
  category: Category;
  description: string;
  liveUrl: string | null;
  customDomain: string | null;
  githubRepo: string | null;
  hosting: string;
  stage: Stage;
  visibleOnShowcase: boolean;
  nextMove: string | null;
  blockers: string | null;
  apiDependencies: string[];
  snap: SnapshotInput;
}

export const APPS: SeedApp[] = [
  // ─── Roof MRI ────────────────────────────────────────────────────────────
  {
    name: "Roof MRI Website",
    slug: "roof-mri-website",
    category: "roofmri",
    description: "Marketing site and PHD Scale reference.",
    liveUrl: "https://roof-mri.com",
    customDomain: "roof-mri.com",
    githubRepo: "adam1capps/roof-mri-main-website",
    hosting: "netlify",
    stage: "mature",
    visibleOnShowcase: true,
    nextMove: "Refresh case-study section with Rackley data.",
    blockers: null,
    apiDependencies: ["SendGrid", "Plausible"],
    snap: { urlStatus: 200, urlResponseMs: 184, lastCommitAt: "2026-04-22", lastCommitMsg: "copy: tighten PHD Scale callouts" },
  },
  {
    name: "Proposals App",
    slug: "proposals-roofmri",
    category: "roofmri",
    description: "Generates Rackley moisture-detection proposals from intake form.",
    liveUrl: "https://proposals.roof-mri.com",
    customDomain: "proposals.roof-mri.com",
    githubRepo: "adam1capps/roof-mri-backend",
    hosting: "netlify+render",
    stage: "live",
    visibleOnShowcase: true,
    nextMove: "Wire Render service health to status dot.",
    blockers: null,
    apiDependencies: ["Anthropic", "Neon", "SendGrid", "Render"],
    snap: { urlStatus: 200, urlResponseMs: 412, lastCommitAt: "2026-05-12", lastCommitMsg: "fix: PDF orientation on letter size" },
  },
  {
    name: "MRI Connect",
    slug: "mri-connect",
    category: "roofmri",
    description: "Contractor portal for certified Rackley installers.",
    liveUrl: "https://connect.roof-mri.com",
    customDomain: "connect.roof-mri.com",
    githubRepo: "adam1capps/roof-mri-connect",
    hosting: "netlify",
    stage: "live",
    visibleOnShowcase: true,
    nextMove: "Add @re-dry.com login gate for staff view.",
    blockers: null,
    apiDependencies: ["Clerk", "Neon"],
    snap: { urlStatus: 200, urlResponseMs: 236, lastCommitAt: "2026-05-09", lastCommitMsg: "feat: certificate verification endpoint" },
  },
  {
    name: "Pro Trainers Presentation",
    slug: "pro-trainers",
    category: "roofmri",
    description: "Slide deck site used in PHD certification classes.",
    liveUrl: "https://protraining.roof-mri.com",
    customDomain: "protraining.roof-mri.com",
    githubRepo: "adam1capps/roof-mri-training-presentation-pro",
    hosting: "netlify",
    stage: "live",
    visibleOnShowcase: true,
    nextMove: "Replace lesson 4 video with re-recorded version.",
    blockers: "Waiting on edited footage from production.",
    apiDependencies: [],
    snap: { urlStatus: 200, urlResponseMs: 198, lastCommitAt: "2026-03-30", lastCommitMsg: "content: add lesson 6 slide notes" },
  },
  {
    name: "App Guide",
    slug: "app-guide",
    category: "roofmri",
    description: "In-product help index for the Roof MRI app suite.",
    liveUrl: "https://appguide.roof-mri.com",
    customDomain: "appguide.roof-mri.com",
    githubRepo: "adam1capps/roof-mri-app-guide",
    hosting: "netlify",
    stage: "live",
    visibleOnShowcase: true,
    nextMove: "Index the warranty app's new screens.",
    blockers: null,
    apiDependencies: [],
    snap: { urlStatus: 200, urlResponseMs: 152, lastCommitAt: "2026-05-02", lastCommitMsg: "docs: vent placement walkthrough" },
  },
  {
    name: "Certificate Generator",
    slug: "certificate-generator",
    category: "roofmri",
    description: "PHD Scale certificate PDFs for trained contractors.",
    liveUrl: "https://certifications.roof-mri.com",
    customDomain: "certifications.roof-mri.com",
    githubRepo: "adam1capps/mri_certificate_generator",
    hosting: "netlify",
    stage: "live",
    visibleOnShowcase: true,
    nextMove: "Pull recipient list from Connect instead of CSV upload.",
    blockers: null,
    apiDependencies: ["Neon"],
    snap: { urlStatus: 200, urlResponseMs: 267, lastCommitAt: "2026-04-18", lastCommitMsg: "feat: batch download zip" },
  },
  {
    name: "Rackley Reports",
    slug: "rackley-reports",
    category: "roofmri",
    description: "Customer-facing moisture report viewer for Rackley jobs.",
    liveUrl: "https://rackley.roof-mri.com",
    customDomain: "rackley.roof-mri.com",
    githubRepo: "adam1capps/rackley-roof-mri-reports",
    hosting: "netlify",
    stage: "live",
    visibleOnShowcase: true,
    nextMove: "Add per-roof drill-down from index page.",
    blockers: null,
    apiDependencies: ["Neon", "Mapbox"],
    snap: { urlStatus: 200, urlResponseMs: 309, lastCommitAt: "2026-05-15", lastCommitMsg: "feat: PDF export with thermal overlay" },
  },
  {
    name: "Warranty Management App",
    slug: "warranty-management",
    category: "roofmri",
    description: "Warranty claim intake and certified-roof registry.",
    liveUrl: "https://warranty-app-kofu.onrender.com",
    customDomain: null,
    githubRepo: "adam1capps/warranty-management-app",
    hosting: "netlify+render",
    stage: "live",
    visibleOnShowcase: false,
    nextMove: "Move from Render free tier to paid; cold starts hurting UX.",
    blockers: null,
    apiDependencies: ["Render", "Neon", "SendGrid"],
    snap: { urlStatus: 200, urlResponseMs: 1840, lastCommitAt: "2026-05-07", lastCommitMsg: "chore: bump renderer image" },
  },
  {
    name: "Training Site",
    slug: "training-site",
    category: "roofmri",
    description: "Legacy training portal predating Pro Trainers.",
    liveUrl: "https://training.roof-mri.com",
    customDomain: "training.roof-mri.com",
    githubRepo: null,
    hosting: "netlify (manual)",
    stage: "polishing",
    visibleOnShowcase: false,
    nextMove: "Decide: redirect to protraining or rehost in a repo.",
    blockers: null,
    apiDependencies: [],
    snap: { urlStatus: 200, urlResponseMs: 178, lastCommitAt: null, lastCommitMsg: null },
  },
  {
    name: "Moisture Detection",
    slug: "moisture-detection",
    category: "roofmri",
    description: "Landing for the moisture-detection training program.",
    liveUrl: "https://moisture-detection.roof-mri.com",
    customDomain: "moisture-detection.roof-mri.com",
    githubRepo: null,
    hosting: "netlify (manual)",
    stage: "polishing",
    visibleOnShowcase: false,
    nextMove: "Move source into a repo; currently only on the Netlify drop.",
    blockers: null,
    apiDependencies: [],
    snap: { urlStatus: 200, urlResponseMs: 202, lastCommitAt: null, lastCommitMsg: null },
  },
  {
    name: "Eric/Adam Example",
    slug: "eric-adam-example",
    category: "roofmri",
    description: "Reference build used to walk Eric through the stack.",
    liveUrl: "https://adamericexample.roof-mri.com",
    customDomain: "adamericexample.roof-mri.com",
    githubRepo: "adam1capps/eric-adam-example",
    hosting: "netlify",
    stage: "live",
    visibleOnShowcase: false,
    nextMove: "Archive once handoff is signed off.",
    blockers: null,
    apiDependencies: [],
    snap: { urlStatus: 200, urlResponseMs: 124, lastCommitAt: "2026-02-04", lastCommitMsg: "walkthrough: routing example" },
  },

  // ─── ReDry ───────────────────────────────────────────────────────────────
  {
    name: "ReDry Website",
    slug: "redry-website",
    category: "redry",
    description: "Main commercial site for the Rapid-Vent rental program.",
    liveUrl: "https://re-dry.com",
    customDomain: "re-dry.com",
    githubRepo: "adam1capps/ReDry-Website",
    hosting: "netlify",
    stage: "mature",
    visibleOnShowcase: true,
    nextMove: "New hero copy from the 2026 messaging refresh.",
    blockers: null,
    apiDependencies: ["SendGrid", "Plausible"],
    snap: { urlStatus: 200, urlResponseMs: 165, lastCommitAt: "2026-04-29", lastCommitMsg: "content: update fleet count" },
  },
  {
    name: "Job Lifecycle / Job Board",
    slug: "job-lifecycle",
    category: "redry",
    description: "Internal board tracking every Rapid-Vent rental from intake to return.",
    liveUrl: "https://jobboard.re-dry.com",
    customDomain: "jobboard.re-dry.com",
    githubRepo: "adam1capps/job_lifecycle_app",
    hosting: "netlify",
    stage: "live",
    visibleOnShowcase: true,
    nextMove: "Surface days-since-status-change on each card.",
    blockers: null,
    apiDependencies: ["Neon", "Clerk", "SendGrid"],
    snap: { urlStatus: 200, urlResponseMs: 289, lastCommitAt: "2026-05-14", lastCommitMsg: "feat: filter by foreman" },
  },
  {
    name: "Flyby (3D)",
    slug: "flyby",
    category: "redry",
    description: "Three.js flyby of a wet roof showing dry-down progression.",
    liveUrl: "https://flyby.re-dry.com",
    customDomain: "flyby.re-dry.com",
    githubRepo: "adam1capps/flyby-redry",
    hosting: "netlify",
    stage: "live",
    visibleOnShowcase: true,
    nextMove: "Bake camera path for the new sales pitch.",
    blockers: null,
    apiDependencies: [],
    snap: { urlStatus: 200, urlResponseMs: 421, lastCommitAt: "2026-05-06", lastCommitMsg: "feat: time-of-day toggle" },
  },
  {
    name: "Vent Placement",
    slug: "vent-placement",
    category: "redry",
    description: "Web app for laying out Rapid-Vents on a roof plan.",
    liveUrl: "https://vents.re-dry.com",
    customDomain: "vents.re-dry.com",
    githubRepo: "adam1capps/redry-vent-placement",
    hosting: "netlify+render",
    stage: "live",
    visibleOnShowcase: true,
    nextMove: "Contractor read-only view with PHD-scale overlay.",
    blockers: null,
    apiDependencies: ["Neon", "Anthropic", "Render"],
    snap: { urlStatus: 200, urlResponseMs: 312, lastCommitAt: "2026-05-16", lastCommitMsg: "feat: address > roof > project tree" },
  },
  {
    name: "Accounting Software",
    slug: "accounting",
    category: "redry",
    description: "Internal-only accounting workspace; replaces QBO export hacks.",
    liveUrl: "https://redry-accounting-app.netlify.app",
    customDomain: null,
    githubRepo: "adam1capps/accounting-software",
    hosting: "netlify",
    stage: "mvp",
    visibleOnShowcase: false,
    nextMove: "Map chart of accounts to the new categories.",
    blockers: "Waiting on bookkeeper signoff for category list.",
    apiDependencies: ["Neon", "Plaid"],
    snap: { urlStatus: 200, urlResponseMs: 341, lastCommitAt: "2026-05-10", lastCommitMsg: "feat: invoice import" },
  },
  {
    name: "Proposal Builder",
    slug: "proposal-builder",
    category: "redry",
    description: "Render-only service that compiles Rapid-Vent proposals from job data.",
    liveUrl: null,
    customDomain: null,
    githubRepo: "adam1capps/redry-proposal-app",
    hosting: "render",
    stage: "mvp",
    visibleOnShowcase: false,
    nextMove: "Front-end shell; service runs but has no UI.",
    blockers: null,
    apiDependencies: ["Render", "Anthropic"],
    snap: { urlStatus: null, urlResponseMs: null, lastCommitAt: "2026-04-26", lastCommitMsg: "feat: scope-of-work generator" },
  },
  {
    name: "Invoice Manager",
    slug: "invoice-manager",
    category: "redry",
    description: "One-off invoice viewer for rental accounts.",
    liveUrl: "https://invoice.re-dry.com",
    customDomain: "invoice.re-dry.com",
    githubRepo: "adam1capps/invoice-manager",
    hosting: "netlify (manual)",
    stage: "polishing",
    visibleOnShowcase: false,
    nextMove: "Reconcile with the new Accounting app; likely deprecate.",
    blockers: null,
    apiDependencies: [],
    snap: { urlStatus: 500, urlResponseMs: 1240, lastCommitAt: "2025-11-04", lastCommitMsg: "fix: stripe webhook idempotency" },
  },
  {
    name: "ReDry Links",
    slug: "redry-links",
    category: "redry",
    description: "Short-link hub used in printed material.",
    liveUrl: "https://redry-links.netlify.app",
    customDomain: null,
    githubRepo: null,
    hosting: "netlify (manual)",
    stage: "live",
    visibleOnShowcase: false,
    nextMove: "Move to a repo so deploys aren't drag-and-drop.",
    blockers: null,
    apiDependencies: [],
    snap: { urlStatus: 200, urlResponseMs: 118, lastCommitAt: null, lastCommitMsg: null },
  },
  {
    name: "LinkedIn Outreach",
    slug: "li-outreach",
    category: "redry",
    description: "Lead-gen target list and message templates for ReDry sales.",
    liveUrl: "https://redry-li-outreach.netlify.app",
    customDomain: null,
    githubRepo: null,
    hosting: "netlify (manual)",
    stage: "live",
    visibleOnShowcase: false,
    nextMove: "Repo it; pair with the LinkedIn App for sending.",
    blockers: null,
    apiDependencies: [],
    snap: { urlStatus: 200, urlResponseMs: 142, lastCommitAt: null, lastCommitMsg: null },
  },
  {
    name: "2026 Internship",
    slug: "internship-2026",
    category: "redry",
    description: "Recruiting page for the 2026 ReDry field internship.",
    liveUrl: "https://redry-2026-internship.netlify.app",
    customDomain: null,
    githubRepo: null,
    hosting: "netlify (manual)",
    stage: "live",
    visibleOnShowcase: false,
    nextMove: "Add custom domain once we choose redry.jobs or careers.re-dry.com.",
    blockers: null,
    apiDependencies: ["SendGrid"],
    snap: { urlStatus: 200, urlResponseMs: 171, lastCommitAt: null, lastCommitMsg: null },
  },

  // ─── MindReadir ──────────────────────────────────────────────────────────
  {
    name: "MindReadir Press Engine",
    slug: "mindreadir-press",
    category: "mindreadir",
    description: "Press-release engine for MindReadir announcements.",
    liveUrl: "https://mindreadir.com",
    customDomain: "mindreadir.com",
    githubRepo: "adam1capps/mindreadir-press-app",
    hosting: "netlify+render",
    stage: "live",
    visibleOnShowcase: true,
    nextMove: "Move LLM calls from Render worker to direct fetch.",
    blockers: null,
    apiDependencies: ["Anthropic", "Render", "Neon", "SendGrid"],
    snap: { urlStatus: 200, urlResponseMs: 498, lastCommitAt: "2026-05-11", lastCommitMsg: "feat: outlet targeting" },
  },

  // ─── Capps Apps ──────────────────────────────────────────────────────────
  {
    name: "LightUp Proposal",
    slug: "lightup",
    category: "cappsapps",
    description: "Consulting proposal landing page for the LightUp engagement.",
    liveUrl: "https://cappsapps.ai/lightup",
    customDomain: "cappsapps.ai",
    githubRepo: "adam1capps/lightup",
    hosting: "netlify",
    stage: "live",
    visibleOnShowcase: true,
    nextMove: "Add scope-extension addendum section.",
    blockers: null,
    apiDependencies: [],
    snap: { urlStatus: 200, urlResponseMs: 108, lastCommitAt: "2026-05-08", lastCommitMsg: "copy: tighten deliverables list" },
  },
  {
    name: "Capps Apps Proposals",
    slug: "cappsapps-proposals",
    category: "cappsapps",
    description: "Template engine for new Capps Apps consulting proposals.",
    liveUrl: null,
    customDomain: null,
    githubRepo: "adam1capps/cappsapps-proposals",
    hosting: "none",
    stage: "building",
    visibleOnShowcase: false,
    nextMove: "Pick a template structure and lock the first three sections.",
    blockers: null,
    apiDependencies: ["Anthropic"],
    snap: { urlStatus: null, urlResponseMs: null, lastCommitAt: "2026-02-19", lastCommitMsg: "scaffold: route shell" },
  },

  // ─── Internal / Other ────────────────────────────────────────────────────
  {
    name: "The Hub App",
    slug: "hub-app",
    category: "internal",
    description: "Internal dispatcher used to route inbound work to the right portfolio app.",
    liveUrl: "https://thehubapp.netlify.app",
    customDomain: null,
    githubRepo: "adam1capps/hub-dispatch",
    hosting: "netlify",
    stage: "live",
    visibleOnShowcase: false,
    nextMove: "Roll into this Command Center.",
    blockers: null,
    apiDependencies: ["Neon"],
    snap: { urlStatus: 200, urlResponseMs: 204, lastCommitAt: "2026-04-11", lastCommitMsg: "feat: routing rule editor" },
  },
  {
    name: "Hub App Scanner",
    slug: "hub-app-scanner",
    category: "internal",
    description: "launchd job that walks the local code directory and reports orphan repos.",
    liveUrl: null,
    customDomain: null,
    githubRepo: "adam1capps/hub-app-scanner",
    hosting: "local",
    stage: "live",
    visibleOnShowcase: false,
    nextMove: "Push results to Neon so the Command Center can read them.",
    blockers: null,
    apiDependencies: ["Neon"],
    snap: { urlStatus: null, urlResponseMs: null, lastCommitAt: "2026-05-13", lastCommitMsg: "feat: detect netlify-only deploys" },
  },
  {
    name: "TaskLine App",
    slug: "taskline",
    category: "internal",
    description: "Personal task line; minimal, single-stream.",
    liveUrl: null,
    customDomain: null,
    githubRepo: "adam1capps/taskline-app",
    hosting: "none",
    stage: "building",
    visibleOnShowcase: false,
    nextMove: "Decide if this stays personal or becomes a portfolio app.",
    blockers: null,
    apiDependencies: [],
    snap: { urlStatus: null, urlResponseMs: null, lastCommitAt: "2026-01-21", lastCommitMsg: "init: schema sketch" },
  },
  {
    name: "Smart Bookkeeper",
    slug: "smart-bookkeeper",
    category: "internal",
    description: "Categorization layer over Plaid transactions for the ReDry books.",
    liveUrl: null,
    customDomain: null,
    githubRepo: "adam1capps/smart-bookkeeper",
    hosting: "none",
    stage: "building",
    visibleOnShowcase: false,
    nextMove: "Fold into the ReDry Accounting app.",
    blockers: null,
    apiDependencies: ["Plaid", "Anthropic"],
    snap: { urlStatus: null, urlResponseMs: null, lastCommitAt: "2026-03-02", lastCommitMsg: "feat: rule engine prototype" },
  },
  {
    name: "LinkedIn App",
    slug: "linkedin-app",
    category: "internal",
    description: "Sender service paired with the ReDry outreach target list.",
    liveUrl: null,
    customDomain: null,
    githubRepo: "adam1capps/linkedin-app",
    hosting: "none",
    stage: "building",
    visibleOnShowcase: false,
    nextMove: "Stalled. Pick up after LinkedIn API approval lands.",
    blockers: "Awaiting LinkedIn Marketing Developer Platform access.",
    apiDependencies: ["LinkedIn"],
    snap: { urlStatus: null, urlResponseMs: null, lastCommitAt: "2026-02-28", lastCommitMsg: "scaffold: auth flow" },
  },
  {
    name: "Gravimetric Readings App",
    slug: "gravimetric-readings",
    category: "internal",
    description: "Logbook for lab gravimetric moisture readings used to calibrate PHD Scale.",
    liveUrl: "https://gravimetrics-app.netlify.app",
    customDomain: null,
    githubRepo: "adam1capps/gravimetric-readings-app",
    hosting: "netlify+render",
    stage: "mvp",
    visibleOnShowcase: false,
    nextMove: "Add CSV import from the lab's USB scale.",
    blockers: null,
    apiDependencies: ["Render", "Neon"],
    snap: { urlStatus: 200, urlResponseMs: 367, lastCommitAt: "2026-04-04", lastCommitMsg: "feat: reading entry form" },
  },
  {
    name: "Grid & Report Workflow",
    slug: "grid-report",
    category: "internal",
    description: "Internal grid editor and report renderer used for ad-hoc QA.",
    liveUrl: "https://helpful-seahorse-755ba9.netlify.app",
    customDomain: null,
    githubRepo: "adam1capps/grid-and-report-workflow",
    hosting: "netlify",
    stage: "mvp",
    visibleOnShowcase: false,
    nextMove: "Give it a custom domain or sunset.",
    blockers: null,
    apiDependencies: [],
    snap: { urlStatus: 404, urlResponseMs: 96, lastCommitAt: "2026-03-19", lastCommitMsg: "feat: report renderer v2" },
  },
  {
    name: "TruHome Experience",
    slug: "truhome",
    category: "internal",
    description: "Client-specific landing experience for the TruHome pilot.",
    liveUrl: "https://truhome-experience.netlify.app",
    customDomain: null,
    githubRepo: "adam1capps/truhomeexperience",
    hosting: "netlify",
    stage: "mvp",
    visibleOnShowcase: false,
    nextMove: "Decide whether TruHome continues; if not, archive.",
    blockers: null,
    apiDependencies: [],
    snap: { urlStatus: 200, urlResponseMs: 221, lastCommitAt: "2026-02-12", lastCommitMsg: "feat: walkthrough video block" },
  },

  // ─── Archive candidates ──────────────────────────────────────────────────
  {
    name: "roof-mri-website (empty)",
    slug: "roof-mri-website-stub",
    category: "roofmri",
    description: "Empty stub repo. Superseded by roof-mri-main-website.",
    liveUrl: null,
    customDomain: null,
    githubRepo: "adam1capps/roof-mri-website",
    hosting: "none",
    stage: "archive",
    visibleOnShowcase: false,
    nextMove: null,
    blockers: null,
    apiDependencies: [],
    snap: { urlStatus: null, urlResponseMs: null, lastCommitAt: "2025-04-02", lastCommitMsg: "init" },
  },
  {
    name: "roof-mri-frontend (stub)",
    slug: "roof-mri-frontend",
    category: "roofmri",
    description: "Empty stub repo. No live deploy.",
    liveUrl: null,
    customDomain: null,
    githubRepo: "adam1capps/roof-mri-frontend",
    hosting: "none",
    stage: "archive",
    visibleOnShowcase: false,
    nextMove: null,
    blockers: null,
    apiDependencies: [],
    snap: { urlStatus: null, urlResponseMs: null, lastCommitAt: "2025-05-18", lastCommitMsg: "init" },
  },
  {
    name: "roofwarrantymanagement (readme)",
    slug: "roofwarrantymanagement",
    category: "roofmri",
    description: "README only. Superseded by warranty-management-app.",
    liveUrl: null,
    customDomain: null,
    githubRepo: "adam1capps/roofwarrantymanagement",
    hosting: "none",
    stage: "archive",
    visibleOnShowcase: false,
    nextMove: null,
    blockers: null,
    apiDependencies: [],
    snap: { urlStatus: null, urlResponseMs: null, lastCommitAt: "2025-07-30", lastCommitMsg: "init README" },
  },
  {
    name: "redry-website-03042026 (dup)",
    slug: "redry-website-dup",
    category: "redry",
    description: "Working-copy duplicate of ReDry-Website. Safe to archive.",
    liveUrl: null,
    customDomain: null,
    githubRepo: "adam1capps/redry-website-03042026",
    hosting: "none",
    stage: "archive",
    visibleOnShowcase: false,
    nextMove: null,
    blockers: null,
    apiDependencies: [],
    snap: { urlStatus: null, urlResponseMs: null, lastCommitAt: "2026-03-04", lastCommitMsg: "backup snapshot" },
  },
  {
    name: "personal-brand (readme)",
    slug: "personal-brand",
    category: "cappsapps",
    description: "README only. Placeholder for a future personal site.",
    liveUrl: null,
    customDomain: null,
    githubRepo: "adam1capps/personal-brand",
    hosting: "none",
    stage: "archive",
    visibleOnShowcase: false,
    nextMove: null,
    blockers: null,
    apiDependencies: [],
    snap: { urlStatus: null, urlResponseMs: null, lastCommitAt: "2025-09-11", lastCommitMsg: "init" },
  },
];
