[build]
  base = "app"
  command = "pnpm install --frozen-lockfile && pnpm build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions."poll-status"]
  schedule = "0 */6 * * *"
